/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp4;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author pierr
 */
public class IHMMap extends javax.swing.JFrame {

    private File fichierMap = new File("src/images/mapLOTR.jpg");
    private File fichierSprite = new File("src/images/sprite.png");
    private File fichierPotion = new File("src/images/potion.png");
    
    private BufferedImage imageMap;
    private BufferedImage imageSprite;
    private BufferedImage imagePotion;
    
    private BufferedImage []tab = new BufferedImage[20];
    
    private int xLink = 100; 
    private int yLink = 100; 
    
    private int indiceLink = 0;
    private int compteurLink = 0;
            
            
    
    

    /**
     * Creates new form IHMMap
     */
    public IHMMap() {
        initComponents();
        setBounds(0, 0, 1800, 1038);
        jPanel1.setFocusable(true);
        
        try 
        {
            imageMap = ImageIO.read(fichierMap); //chargement
            imageSprite = ImageIO.read(fichierSprite);
            imagePotion = ImageIO.read(fichierPotion);
            
            for (int i = 0; i < 20; i++) 
            {
                int colonne = i % 5;
                int ligne = i / 5;
                
                int x = colonne * 90;
                int y = ligne * 90;
                
                tab[i] = imageSprite.getSubimage(x, y, 90, 90);
            }
            
        } catch (IOException ex) {
            System.out.println("fichier introuvable");
        }

    }
    /**

     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g)
            {
                g.drawImage(imageMap, 0, 0, null);
                g.drawImage(tab[indiceLink + compteurLink], xLink, yLink, null);
                g.drawImage(imagePotion, 900, 500, null);
            }
        }
        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        xLink = evt.getX();
        yLink = evt.getY();
        
        jPanel1.repaint();
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        
        if(evt.getKeyChar()== 'z'){
            indiceLink = 10; 
            compteurLink += 1; 
            yLink -= 10;} //vers le haut
            
         if(evt.getKeyChar()== 'q'){
            indiceLink = 0; 
            compteurLink += 1; 
            xLink -= 10;} //vers la gauche
        
         if(evt.getKeyChar()== 's'){
             indiceLink = 15; 
             compteurLink += 1; 
            yLink += 10;} //vers le bas
            
         if(evt.getKeyChar()== 'd'){
             indiceLink = 5; 
             compteurLink += 1; 
            xLink += 10;} // vers la droite
         
        
         if(compteurLink == 5){
             compteurLink = 0;
         }
         
        traitementPotion();
        traitementBornes();
      
        jPanel1.repaint();
    }//GEN-LAST:event_jPanel1KeyPressed
    
    private void traitementBornes()
    {
        
        if(xLink < -90){ //90 rpz l'orientation du perso 
            xLink = 1800;
        }
        
        if(xLink > 1800){
            xLink = -90;
        }
        
        if(yLink < -90){
            yLink = 1038;    
        }
        
        if(yLink > 1038){
            yLink = -90;  
        }
    }
    private void traitementPotion(){ //gère collision du perso et la potion 
        
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHMMap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
